/**
 * Import full O*NET-SOC 2019 dataset into socOccupationsSeed.ts
 *
 * Usage:
 * 1. Download O*NET-SOC taxonomy JSON/CSV to lib/h1b/data/onet-soc-2019.json
 * 2. Run: npx tsx scripts/import-onet-soc.ts
 */
import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import {
  mapOnetRecordsToOccupations,
  type OnetSocSourceRecord,
} from "../lib/h1b/data/onetSocImport";

const sourcePath = join(process.cwd(), "lib/h1b/data/onet-soc-2019.json");

function main() {
  const raw = readFileSync(sourcePath, "utf8");
  const records = JSON.parse(raw) as OnetSocSourceRecord[];
  const occupations = mapOnetRecordsToOccupations(records);

  const outputPath = join(process.cwd(), "lib/h1b/data/socOccupationsSeed.ts");
  const fileContents = `/**
 * AUTO-GENERATED by scripts/import-onet-soc.ts from O*NET-SOC 2019 source file.
 * Do not edit manually.
 */

import type { SocOccupationEntry } from "@/lib/h1b/types/socOccupation";

export const SOC_OCCUPATIONS_SEED: SocOccupationEntry[] = ${JSON.stringify(occupations, null, 2)} as SocOccupationEntry[];

export const SOC_OCCUPATIONS_SEED_COUNT = ${occupations.length};
`;

  writeFileSync(outputPath, fileContents, "utf8");
  console.log(`Imported ${occupations.length} occupations to ${outputPath}`);
}

main();
